---
- name: Disable selinux
  shell: "setenforce 0"

- name: Ensure selinux is set to permissive mode
  ansible.builtin.lineinfile:
    path: /etc/selinux/config
    regexp: "^SELINUX="
    line: SELINUX=permissive

- name: Add a line kubernetes systemctl configuration
  ansible.builtin.lineinfile:
    path: /etc/sysctl.d/k8s.conf
    line: "{{ item }}"
    create: yes
  with_items:
    - net.bridge.bridge-nf-call-ip6tables = 1
    - net.bridge.bridge-nf-call-iptables = 1
    - net.ipv4.ip_forward = 1

- name: Apply systemctl configuration
  shell: sysctl --system

- name: Get kubectl stable version
  ansible.builtin.uri:
    url: https://dl.k8s.io/release/stable.txt
    return_content: yes
  register: latest_kubectl
  until: latest_kubectl.status == 200
  delay: 10
  retries: 3

- name: Download kubectl
  ansible.builtin.get_url:
    url: "https://dl.k8s.io/release/{{ latest_kubectl.content }}/bin/linux/amd64/kubectl"
    dest: /root
  register: download
  until: download.status_code == 200
  delay: 10
  retries: 3

- name: Install kubectl
  shell: install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

- name: Remove kubectl file
  ansible.builtin.file:
    path: "./get_helm.sh"
    state: absent

- name: Yum install bash-completion
  yum:
    name: bash-completion
    state: present

- name: Source BashCompletion
  shell: "echo 'source <(kubectl completion bash)' >> ~/.bashrc"

- name: Add a line kubectl alias
  ansible.builtin.lineinfile:
    path: ~/.bashrc
    line: "{{ item }}"
  with_items:
    - alias k=kubectl
    - complete -F __start_kubectl k
